### PR TITLE
Fix exception thrown when enumerating

### LINKED ISSUE #22: Exception thrown when enumerating file with differing number of values in the first data row
An exception is thrown when attempting to use DelimitedDataParser to parse a file which has a different number of values in its first data row compared to the number of values in the header row, when enumerating the reader returned by `DelimitedDataParser.Parser.ParseReader()`.

For example, the following file will fail to be parsed:

> Col1,Col2,Col3
> val1,val2
> val3,val4,val5

It does appear that differing number of values per row is supported. For example, the following file can be parsed without issue:

> Col1,Col2,Col3
> val1,val2,val3
> val4,val5

So the problem only appears to be when the *first* data row has a differing number of elements.

The following code can be used to reproduce this issue:

```csharp
using System.IO;
using DelimitedDataParser;

public class Program
{
    public static void Main(string[] args)
    {
        var content = @"Col1,Col2,Col3
val1,val2
val3,val4,val5";

        using (var stringReader = new StringReader(content))
        {
            var parser = new DelimitedDataParser.Parser
            {
                UseFirstRowAsColumnHeaders = true
            };

            var reader = parser.ParseReader(stringReader);
            var enumerator = reader.GetEnumerator();

            while (enumerator.MoveNext()) // This line will throw.
            {
                // …
            }
        }
    }
}
```

The line `enumerator.MoveNext()`, above, throws the following exception:

    ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
    Parameter name: ordinal
    at DelimitedDataParser.DelimitedDataReader.GetFieldType(Int32 ordinal)
    at System.Data.Common.DbEnumerator.BuildSchemaInfo()
    at System.Data.Common.DbEnumerator.MoveNext()
    // Stack trace truncated…

Interestingly, working with the `DbDataReader` returned by `ParserReader()` directly, rather than using an enumerator works as expected. For example, the following code *does not* throw:

```csharp
// Preceeding code is unchanged from previous code sample provided.
var reader = parser.ParseReader(stringReader);

while (reader.Read()) // This line does not throw.
{
    // …
```

### PR DESCRIPTION
**Pull request by michaelsw95**
Modify range checks to exclude case where we have just stepped the first row.

Resolves #22.

### CODE REVIEW

File: src/DelimitedDataParser/DelimitedDataReader.cs [hunk 1]
```diff
@@ -253,7 +253,7 @@ public override long GetChars(int ordinal, long dataOffset, char[] buffer, int b
 
         public override string GetDataTypeName(int ordinal)
         {
-            if (ordinal < 0 || ordinal > _currentRow.Count - 1)
+            if (!_yieldExistingRow && (ordinal < 0 || ordinal > _currentRow.Count - 1))
```
Comment (cgwrench) [inline src/DelimitedDataParser/DelimitedDataReader.cs]: This change appears to be disabling argument range checking if we're due to "yield an existing row". Should we not instead be modifying the checks that we perform depending on whether `_yieldExistingRow` is set? For example, if this is `false`, then we check against `_fieldNameLookup.Count`, otherwise we check against `_currentRow.Count`?

File: src/DelimitedDataParser/DelimitedDataReader.cs [hunk 2]
```diff
@@ -304,7 +304,7 @@ public override IEnumerator GetEnumerator()
 
         public override Type GetFieldType(int ordinal)
         {
-            if (ordinal < 0 || ordinal > _currentRow.Count - 1)
+            if (!_yieldExistingRow && (ordinal < 0 || ordinal > _currentRow.Count - 1))
```
Comment (cgwrench) [inline src/DelimitedDataParser/DelimitedDataReader.cs]: As above. Should we not instead be modifying the checks that we perform depending on whether `_yieldExistingRow` is set? For example, if this is `false`, then we check against `_fieldNameLookup.Count`, otherwise we check against `_currentRow.Count`?

File: test/DelimitedDataParser.Test/ParserTest.Reader.cs [hunk 3]
```diff
@@ -1892,5 +1893,87 @@ public void ParseReader_HasRows_ReturnsTrueForHeaderAndDataRows()
...
+                Assert.Equal("Data 6", current[0]);
+                Assert.Equal("Data 7", current[1]);
+                Assert.Equal("Data 8", current[2]);
+            }
+        }
+
+        [Fact]
+        public void Supports_Varying_Column_Counts_In_Enumerator_Without_Column_Headers()
+        {
+            var content = @"Field 1,Field 2,Field 3" + Environment.NewLine
```
Comment (cgwrench) [inline test/DelimitedDataParser.Test/ParserTest.Reader.cs]: We should call this variable `input` for consistency with the existing tests.

File: test/DelimitedDataParser.Test/ParserTest.Reader.cs [hunk 4]
```diff
@@ -1892,5 +1893,87 @@ public void ParseReader_HasRows_ReturnsTrueForHeaderAndDataRows()
 
             Assert.True(reader.HasRows);
         }
+
+        [Fact]
+        public void Supports_Varying_Column_Counts_In_Enumerator_With_Column_Headers()
+        {
+            var content = @"Field 1,Field 2,Field 3" + Environment.NewLine
```
Comment (cgwrench) [inline test/DelimitedDataParser.Test/ParserTest.Reader.cs]: We should call this variable `input` for consistency with the existing tests.

File: test/DelimitedDataParser.Test/ParserTest.Reader.cs [hunk 5]
```diff
@@ -1892,5 +1893,87 @@ public void ParseReader_HasRows_ReturnsTrueForHeaderAndDataRows()
...
+            }
+        }
+
+        [Fact]
+        public void Supports_Varying_Column_Counts_In_Enumerator_Without_Column_Headers()
+        {
+            var content = @"Field 1,Field 2,Field 3" + Environment.NewLine
+                + @"Data 1,Data 2" + Environment.NewLine
+                + @"Data 5" + Environment.NewLine
+                + @"Data 6,Data 7,Data 8, data 9";
```
Comment (cgwrench) [inline test/DelimitedDataParser.Test/ParserTest.Reader.cs]: Could we modify this test case to use the same example as provided in #22? We don't need three data rows to reproduce the reported issue.

File: test/DelimitedDataParser.Test/ParserTest.Reader.cs [hunk 6]
```diff
@@ -1892,5 +1893,87 @@ public void ParseReader_HasRows_ReturnsTrueForHeaderAndDataRows()
...
             Assert.True(reader.HasRows);
         }
+
+        [Fact]
+        public void Supports_Varying_Column_Counts_In_Enumerator_With_Column_Headers()
+        {
+            var content = @"Field 1,Field 2,Field 3" + Environment.NewLine
+                + @"Data 1,Data 2" + Environment.NewLine
+                + @"Data 5" + Environment.NewLine
+                + @"Data 6,Data 7,Data 8, data 9";
```
Comment (cgwrench) [inline test/DelimitedDataParser.Test/ParserTest.Reader.cs]: Could we modify this test case to use the same example as provided in #22? We don't need three data rows to reproduce the reported issue.

File: test/DelimitedDataParser.Test/ParserTest.Reader.cs [hunk 7]
```diff
@@ -1892,5 +1893,87 @@ public void ParseReader_HasRows_ReturnsTrueForHeaderAndDataRows()
...
+
+            using (var stringReader = new StringReader(content))
```
Comment (cgwrench) [inline test/DelimitedDataParser.Test/ParserTest.Reader.cs]: This test appears to be inconsistent with existing tests in the way that it is parsing the test input. Let's modify this test to make use of `GetTextReader()`, rather working with a `StringReader` directly.

File: test/DelimitedDataParser.Test/ParserTest.Reader.cs [hunk 8]
```diff
@@ -1892,5 +1893,87 @@ public void ParseReader_HasRows_ReturnsTrueForHeaderAndDataRows()
...
+
+        [Fact]
+        public void Supports_Varying_Column_Counts_In_Enumerator_Without_Column_Headers()
+        {
+            var content = @"Field 1,Field 2,Field 3" + Environment.NewLine
+                + @"Data 1,Data 2" + Environment.NewLine
+                + @"Data 5" + Environment.NewLine
+                + @"Data 6,Data 7,Data 8, data 9";
+
+            using (var stringReader = new StringReader(content))
```
Comment (cgwrench) [inline test/DelimitedDataParser.Test/ParserTest.Reader.cs]: This test appears to be inconsistent with existing tests in the way that it is parsing the test input. Let's modify this test to make use of `GetTextReader()`, rather working with a `StringReader` directly.

**Review by cgwrench — CHANGES_REQUESTED** [review]

**Review by cgwrench — APPROVED** [review]
